substitutions:
  name: 3_smart_buttons
  friendly_name: "3 Smart Buttons"

esphome:
  name: $name
  platform: ESP8266
  board: d1_mini
  on_boot:
    - light.turn_on:
        id: led_1
    - light.turn_on:
        id: led_2
    - light.turn_on:
        id: led_3

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key:

ota:
  password:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid:
    password:

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: "Button 1"
#    device_class: opening

  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: "Button 2"
#    device_class: opening

  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: "Button 3"
#    device_class: opening

light:
  - platform: binary
    name: "LED 1"
    output: light_output1
    id: led_1

  - platform: binary
    name: "LED 2"
    output: light_output2
    id: led_2

  - platform: binary
    name: "LED 3"
    output: light_output3
    id: led_3

output:
  - id: light_output1
    platform: gpio
    pin:
      number: D2

  - id: light_output2
    platform: gpio
    pin:
      number: D7

  - id: light_output3
    platform: gpio
    pin:
      number: D0
